name: E2E-test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Шаг для клонирования репозитория Local Env
      - name: Check out Local Env code
        uses: actions/checkout@v2
        with:
          repository: Tosik43/to-dos-local-env 
          path: to-dos-local-env

      # Шаг для клонирования репозитория UI
      - name: Check out UI code
        uses: actions/checkout@v2
        with:
          repository: Tosik43/to-dos-ui
          path: to-dos-ui

      # Шаг для запуска Local Env через devcontainer
      - name: Run Local Env in Dev Container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cd to-dos-local-env
            npm run start-local-env &
          checkoutPath: to-dos-local-env
          
      # Шаг для сборки и запуска Docker-образа UI
      - name: Build UI Docker image
        run: |
          cd to-dos-ui
          docker build -t to-dos-ui .

      # Шаг для запуска тестов Cypress
      - name: Run E2E Tests
        run: |
          cd to-dos-ui
          npm ci
          npm run start-local-env &
          npm run cypress:run:e2e:local-env

      # Шаг для остановки Local Env
      - name: Stop Local Env
        if: always()  
        run: |
          docker stop to-dos-local-env || true
          docker rm to-dos-local-env || true
